---
title: Gebruik grafische effecten
hero_image: images/banner.png
description: Gebruik grafische effecten om kleur, transparantie, helderheid en meer effecten op sprites en het werkgebied te wijzigen en in te stellen
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Gebruik grafische effecten

