---
title: Gebruik grafische effecten
hero_image: images/banner.png
description: Use graphic effects to change and set color, ghost, brightness, and other effects for sprites and the Stage
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Gebruik grafische effecten

