title: scratch3-graphic-effects
hero_image: images/banner.png
description: scratch3-graphic-effects description
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
