---
title: Use graphic effects
hero_image: प्रतिमा / banner.png
description: Use graphic effects to change and set color, ghost, brightness, and other effects for sprites and the Stage
version: 0
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Use graphic effects

