---
title: Sebenzisa iziphumo zokuzoba ngekhompyutha
hero_image: images/banner.png
description: Sebenzisa iziphumo zokuzoba ngekhompyutha ukutshintsha kunye nokumisela umbala, ubufiliba, ukuqaqamba, kunye nezinye iziphumo zesprites kunye neQonga
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Sebenzisa iziphumo zokuzoba ngekhompyutha

