
title: Koristi grafičke efekte
hero_image: images/banner.png
description: Koristi grafičke efekte za promjenu i postavljanje boje, efekta duha, svjetline i drugih efekata za likove i pozornicu
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Koristi grafičke efekte

