---
title: Defnyddio effeithiau graffeg
hero_image: images/banner.png
description: Defnyddio effeithiau graffeg i newid a gosod lliw, ysbryd, disgleirdeb, ac effeithiau eraill ar gyfer corluniau a'r Llwyfan
version: 3
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Defnyddio effeithiau graffeg

