---
title: Verwende Grafikeffekte
hero_image: images/banner.png
description: Verwende Grafikeffekte, um Farben, Geisterbilder, Helligkeiten und andere Effekte für Figuren und die Bühne zu ändern und einzustellen
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Verwende Grafikeffekte

