---
title: Verwende Grafikeffekte
hero_image: images/banner.png
description: Verwende Grafikeffekte, um Farbe, Durchsichtigkeit, Helligkeit und andere Effekte f체r Figuren sowie f체r die B체hne zu 채ndern und einzustellen
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Verwende Grafikeffekte

