---
title: Use efeitos gráficos
hero_image: images/banner.png
description: Utilize efeitos gráficos para mudar ou definir cor, efeito fantasma, brilho e outros efeitos em atores e no Palco
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Use efeitos gráficos

