---
title: Používejte grafické efekty
hero_image: images/banner.png
description: Pomocí grafických efektů můžete změnit a nastavit barvu, duchy, jas a další efekty pro skřítky a plochu
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Používejte grafické efekty

