---
title: Usa efectos gráficos
hero_image: images/banner.png
description: Usa efectos gráficos para cambiar y fijar color, desvanecer, brillo, y otros efectos para los objetos y el Escenario
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Usa efectos gráficos

