---
title: Użyj efektów graficznych
hero_image: images/banner.png
description: Używaj efektów graficznych, aby zmieniać i ustawiać kolor, efekt ducha, jasność i inne efekty duszków i sceny
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Użyj efektów graficznych

