---
title: Använd bildeffekter
hero_image: images/banner.png
description: Använd bildeffekter för att ändra och ställa in färg, spöke, ljusstyrka och andra effekter på sprajterna och scenen
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Använd bildeffekter

