---
title: Χρησιμοποιήστε γραφικά εφέ
hero_image: images/banner.png
description: Χρησιμοποιήστε εφέ γραφικών για να αλλάξετε και να ορίσετε χρώμα, φάντασμα, φωτεινότητα και άλλα εφέ για τα sprites και το Stage
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Χρησιμοποιήστε γραφικά εφέ

