---
title: Utiliser des effets graphiques
hero_image: images/banner.png
description: Utiliser des effets graphiques pour modifier et définir la couleur, la transparence, la luminosité et plus d'effets sur les sprites et la scène.
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Utiliser des effets graphiques

