---
title: Usa effetti grafici
hero_image: images/banner.png
description: Usa effetti grafici per cambiare e impostare il colore, la trasparenza, la luminosità e altri effetti per gli sprite sullo Stage
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Usa effetti grafici

